---
# Title: role-meshcentral2
#
# Author: bitfinity-nl
# File: tasks/mongodb.yml
#
# Description:
#   Remote Management Server

- name: "Install packages"
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: present
  with_items:
    - mongodb

- name: "Start and enable mongodb services"
  systemd:
    name: mongodb
    state: started
    enabled: yes

#- name: "Configure MongoDB"