---
# Title: role-meshcentral2
#
# Author: bitfinity-nl
# File: tasks/mongodb.yml
#
# Description:
#   Remote Management Server

- name: "Install packages"
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: present
  vars:
    packages:
    - mongodb

- name: "Start and enable mongodb services"
  systemd:
    name: mongodb
    state: started
    enabled: yes

- name: "Configure MongoDB in /opt/meshcentral/meshcentral-data/config.json"
  replace:
    path: /opt/meshcentral/meshcentral-data/config.json
    regexp: '_MongoDb'
    replace: 'MongoDb'
  with_items:
    - { regexp: '_MongoDb', replace: 'MongoDb' }
    - { regexp: '_MongoDbName', replace: 'MongoDbName' }    